import { WorkItem, Sprint, KanbanBoard, User } from '../types';
import { EPIC_COLUMNS, FEATURE_COLUMNS, PRODUCT_COLUMNS, TEAM_COLUMNS } from './boardConfig';

export const mockUsers: User[] = [
  { id: '1', name: 'John Doe', email: 'john@example.com', roles: ['program-owner', 'business-owner'] },
  { id: '2', name: 'Jane Smith', email: 'jane@example.com', roles: ['product-owner', 'scrum-master'] },
  { id: '3', name: 'Bob Johnson', email: 'bob@example.com', roles: ['development-team', 'team-lead'] },
];

export const mockWorkItems: WorkItem[] = [
  // Epics
  {
    id: 'epic-1',
    type: 'epic',
    title: 'Epic 1',
    description: 'First epic description',
    status: 'funnel',
    priority: 'high',
    color: '#ef4444',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'epic-2',
    type: 'epic',
    title: 'Epic 2',
    description: 'Second epic description',
    status: 'backlog',
    priority: 'medium',
    color: '#8b5cf6',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'epic-3',
    type: 'epic',
    title: 'Epic 3',
    description: 'Third epic description',
    status: 'analysis',
    priority: 'high',
    color: '#f97316',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'epic-4',
    type: 'epic',
    title: 'Epic 4',
    description: 'Fourth epic description',
    status: 'prioritization',
    priority: 'critical',
    color: '#10b981',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    childrenIds: ['feature-2', 'feature-3'],
  },
  // Features
  {
    id: 'feature-1',
    type: 'feature',
    title: 'Feature 1',
    description: 'First feature description',
    status: 'define',
    priority: 'high',
    parentId: 'epic-3',
    color: '#f97316',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'feature-2',
    type: 'feature',
    title: 'Feature 2',
    description: 'Second feature description',
    status: 'design',
    priority: 'medium',
    parentId: 'epic-4',
    color: '#10b981',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    childrenIds: ['story-1', 'story-3'],
  },
  {
    id: 'feature-3',
    type: 'feature',
    title: 'Feature 3',
    description: 'Third feature description',
    status: 'develop',
    priority: 'high',
    parentId: 'epic-4',
    color: '#fbbf24',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'feature-4',
    type: 'feature',
    title: 'Feature 4',
    description: 'Fourth feature description',
    status: 'release',
    priority: 'low',
    color: '#10b981',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  // Stories
  {
    id: 'story-1',
    type: 'story',
    title: 'Story 1',
    description: 'First story description',
    status: 'in-progress',
    priority: 'high',
    parentId: 'feature-2',
    sprintId: 'sprint-1',
    color: '#10b981',
    estimatedHours: 8,
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
  },
  {
    id: 'story-2',
    type: 'story',
    title: 'Story 2',
    description: 'Second story description',
    status: 'to-do',
    priority: 'medium',
    sprintId: 'sprint-1',
    color: '#fbbf24',
    estimatedHours: 4,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'story-3',
    type: 'story',
    title: 'Story 3',
    description: 'Third story description',
    status: 'in-progress',
    priority: 'high',
    parentId: 'feature-2',
    sprintId: 'sprint-1',
    color: '#10b981',
    estimatedHours: 12,
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
];

export const mockSprints: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 1',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-01-29'),
    status: 'in-progress',
    workItemIds: ['story-1', 'story-2', 'story-3'],
  },
  {
    id: 'sprint-2',
    name: 'Sprint 2',
    startDate: new Date('2024-01-30'),
    endDate: new Date('2024-02-13'),
    status: 'upcoming',
    workItemIds: [],
  },
  {
    id: 'sprint-3',
    name: 'Sprint 3',
    startDate: new Date('2024-02-14'),
    endDate: new Date('2024-02-28'),
    status: 'upcoming',
    workItemIds: [],
  },
];

export const mockBoards: KanbanBoard[] = [
  {
    id: 'epic-board',
    name: 'Epic Board',
    level: 'epic',
    columns: EPIC_COLUMNS,
    workItemIds: ['epic-1', 'epic-2', 'epic-3', 'epic-4'],
  },
  {
    id: 'feature-board',
    name: 'Feature Board',
    level: 'feature',
    columns: FEATURE_COLUMNS,
    workItemIds: ['feature-1', 'feature-2', 'feature-3', 'feature-4'],
  },
  {
    id: 'product-board',
    name: 'Product Board',
    level: 'product',
    columns: PRODUCT_COLUMNS,
    workItemIds: ['story-1', 'story-2', 'story-3'],
  },
  {
    id: 'team-board',
    name: 'Team Board',
    level: 'team',
    columns: TEAM_COLUMNS,
    workItemIds: ['story-1', 'story-2', 'story-3'],
  },
];
