import { WorkItem, Sprint, KanbanBoard, User, TenantCompany } from '../types';
import { EPIC_COLUMNS, FEATURE_COLUMNS, PRODUCT_COLUMNS, TEAM_COLUMNS } from './boardConfig';

/** Seed tenant id for dev when no Firestore companies exist. Not used in production. */
export const SEED_TENANT_ID = 'seed-tenant-1';

/** True only in dev or when VITE_ENABLE_SEED=true. Production must not use seed/Seed Company. */
export const isSeedEnabled = (): boolean =>
  import.meta.env.DEV || import.meta.env.VITE_ENABLE_SEED === 'true';

/** Tenant companies (Firestore companies collection) for dev/mock. */
export const mockTenantCompanies: TenantCompany[] = [
  { id: SEED_TENANT_ID, name: 'Seed Company', slug: 'seed-company', createdAt: new Date('2024-01-00'), updatedAt: new Date('2024-01-00'), seats: 50, companyType: 'software' },
];

export const mockUsers: User[] = [
  { id: '1', name: 'John Doe', email: 'john@example.com', roles: ['portfolio-leader', 'business-owner'] },
  { id: '2', name: 'Jane Smith', email: 'jane@example.com', roles: ['product-owner', 'scrum-master-team-coach'] },
  { id: '3', name: 'Bob Johnson', email: 'bob@example.com', roles: ['developer', 'epic-owner'] },
];

export const mockWorkItems: WorkItem[] = [
  // Companies (in-tenant work item type)
  {
    id: 'company-1',
    type: 'company',
    title: 'Acme Corp',
    description: 'Main company',
    status: 'backlog',
    priority: 'high',
    companyId: SEED_TENANT_ID,
    createdAt: new Date('2024-01-00'),
    updatedAt: new Date('2024-01-00'),
    childrenIds: ['product-1'],
  },
  {
    id: 'company-2',
    type: 'company',
    title: 'Beta Inc',
    description: 'Second company',
    status: 'backlog',
    priority: 'medium',
    companyId: SEED_TENANT_ID,
    createdAt: new Date('2024-01-00'),
    updatedAt: new Date('2024-01-00'),
    childrenIds: [],
  },
  // Products
  {
    id: 'product-1',
    type: 'product',
    title: 'Product Alpha',
    companyId: SEED_TENANT_ID,
    description: 'Main product line',
    status: 'backlog',
    priority: 'high',
    color: '#3b82f6',
    parentId: 'company-1',
    createdAt: new Date('2024-01-00'),
    updatedAt: new Date('2024-01-00'),
    childrenIds: ['epic-1', 'epic-2'],
  },
  // Epics
  {
    id: 'epic-1',
    type: 'epic',
    title: 'Epic 1',
    description: 'First epic description',
    status: 'funnel',
    priority: 'high',
    size: 'large',
    color: '#ef4444',
    parentId: 'product-1',
    companyId: SEED_TENANT_ID,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'epic-2',
    type: 'epic',
    title: 'Epic 2',
    description: 'Second epic description',
    status: 'backlog',
    priority: 'medium',
    size: 'medium',
    color: '#8b5cf6',
    parentId: 'product-1',
    companyId: SEED_TENANT_ID,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'epic-3',
    type: 'epic',
    title: 'Epic 3',
    description: 'Third epic description',
    status: 'analysis',
    priority: 'high',
    size: 'xlarge',
    companyId: SEED_TENANT_ID,
    color: '#f97316',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    childrenIds: ['feature-1'],
  },
  {
    id: 'epic-4',
    type: 'epic',
    title: 'Epic 4',
    description: 'Fourth epic description',
    status: 'prioritization',
    priority: 'critical',
    size: 'large',
    color: '#10b981',
    companyId: SEED_TENANT_ID,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
    childrenIds: ['feature-2', 'feature-3'],
  },
  // Features
  {
    id: 'feature-1',
    type: 'feature',
    title: 'Feature 1',
    description: 'First feature description',
    status: 'funnel',
    priority: 'high',
    size: 'medium',
    parentId: 'epic-3',
    companyId: SEED_TENANT_ID,
    color: '#f97316',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'feature-2',
    type: 'feature',
    title: 'Feature 2',
    description: 'Second feature description',
    status: 'program-backlog',
    priority: 'medium',
    size: 'large',
    parentId: 'epic-4',
    companyId: SEED_TENANT_ID,
    color: '#10b981',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    childrenIds: ['story-1', 'story-3'],
  },
  {
    id: 'feature-3',
    type: 'feature',
    title: 'Feature 3',
    description: 'Third feature description',
    status: 'implementation',
    priority: 'high',
    size: 'medium',
    parentId: 'epic-4',
    companyId: SEED_TENANT_ID,
    color: '#fbbf24',
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
  },
  {
    id: 'feature-4',
    type: 'feature',
    title: 'Feature 4',
    description: 'Fourth feature description',
    status: 'releasing',
    priority: 'low',
    size: 'small',
    companyId: SEED_TENANT_ID,
    color: '#10b981',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  // User Stories
  {
    id: 'story-1',
    type: 'user-story',
    title: 'Story 1',
    description: 'First user story description',
    status: 'in-progress',
    priority: 'high',
    parentId: 'feature-2',
    companyId: SEED_TENANT_ID,
    sprintId: 'sprint-1',
    color: '#10b981',
    storyPoints: 8,
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
    childrenIds: ['task-1', 'task-2'],
  },
  {
    id: 'story-2',
    type: 'user-story',
    title: 'Story 2',
    description: 'Second user story description',
    status: 'to-do',
    priority: 'medium',
    companyId: SEED_TENANT_ID,
    sprintId: 'sprint-1',
    color: '#fbbf24',
    storyPoints: 5,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'story-3',
    type: 'user-story',
    title: 'Story 3',
    description: 'Third user story description',
    status: 'in-progress',
    priority: 'high',
    parentId: 'feature-2',
    companyId: SEED_TENANT_ID,
    sprintId: 'sprint-1',
    color: '#10b981',
    storyPoints: 13,
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    childrenIds: ['bug-1'],
  },
  // Tasks
  {
    id: 'task-1',
    type: 'task',
    title: 'Implement login API',
    description: 'Backend endpoint for user login',
    status: 'done',
    priority: 'high',
    parentId: 'story-1',
    companyId: SEED_TENANT_ID,
    color: '#6b7280',
    estimatedDays: 1,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'task-2',
    type: 'task',
    title: 'Add validation',
    description: 'Client-side form validation',
    status: 'in-progress',
    priority: 'medium',
    parentId: 'story-1',
    companyId: SEED_TENANT_ID,
    color: '#10b981',
    estimatedDays: 0.5,
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  // Bugs
  {
    id: 'bug-1',
    type: 'bug',
    title: 'Login fails on Safari',
    description: 'Authentication fails on Safari browser',
    status: 'to-do',
    priority: 'critical',
    parentId: 'story-3',
    companyId: SEED_TENANT_ID,
    color: '#ef4444',
    estimatedDays: 1,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
];

export const mockSprints: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 1',
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-01-29'),
    status: 'in-progress',
    workItemIds: ['story-1', 'story-2', 'story-3', 'task-1', 'task-2', 'bug-1'],
  },
  {
    id: 'sprint-2',
    name: 'Sprint 2',
    startDate: new Date('2024-01-30'),
    endDate: new Date('2024-02-13'),
    status: 'upcoming',
    workItemIds: [],
  },
  {
    id: 'sprint-3',
    name: 'Sprint 3',
    startDate: new Date('2024-02-14'),
    endDate: new Date('2024-02-28'),
    status: 'upcoming',
    workItemIds: [],
  },
];

export const mockBoards: KanbanBoard[] = [
  {
    id: 'epic-board',
    name: 'Epic Board',
    level: 'epic',
    columns: EPIC_COLUMNS,
    workItemIds: ['epic-1', 'epic-2', 'epic-3', 'epic-4'],
  },
  {
    id: 'feature-board',
    name: 'Feature Board',
    level: 'feature',
    columns: FEATURE_COLUMNS,
    workItemIds: ['feature-1', 'feature-2', 'feature-3', 'feature-4'],
  },
  {
    id: 'product-board',
    name: 'Product Board',
    level: 'product',
    columns: PRODUCT_COLUMNS,
    workItemIds: ['story-1', 'story-2', 'story-3', 'task-1', 'task-2', 'bug-1'],
  },
  {
    id: 'team-board',
    name: 'Team Board',
    level: 'team',
    columns: TEAM_COLUMNS,
    workItemIds: ['story-1', 'story-2', 'story-3', 'task-1', 'task-2', 'bug-1'],
  },
];
